# Generated by Django 5.0.7 on 2024-07-21 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='No description provided'),
        ),
    ]
